# 1. Imports and loading the data

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("Netflix.csv")

In [3]:
dataset

,customer_id,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,a9b75100-82a8-427a-a208-72f24052884a,51.0,Other,Basic,14.73,29.0,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47.0,Other,Standard,0.70,19.0,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27.0,Female,Standard,16.32,10.0,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53.0,Other,Premium,4.51,12.0,Oceania,TV,17.99,1,Crypto,2,0.35,Horror
4,4e265c34-103a-4dbb-9553-76c9aa47e946,56.0,Other,Standard,1.89,13.0,Africa,Mobile,13.99,1,Crypto,2,0.13,Action
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,44f3ba44-b95d-4e50-a786-bac4d06f4a43,19.0,Female,Basic,49.17,11.0,Europe,Desktop,8.99,0,Credit Card,4,4.10,Drama
4996,18779bcb-ba2b-41da-b751-e70b812061ec,67.0,Female,Basic,9.24,2.0,North America,Desktop,8.99,0,PayPal,3,3.08,Documentary
4997,3f32e8c5-615b-4a3b-a864-db2688f7834f,66.0,Male,Standard,16.55,49.0,South America,Desktop,13.99,1,Debit Card,2,0.33,Action
4998,7b0ad82d-6571-430e-90f4-906259e0e89c,59.0,Female,Basic,9.12,3.0,Europe,Laptop,8.99,0,Credit Card,4,2.28,Sci-Fi
4999,82aeef39-ddb0-40ad-bae1-5c436e0cf042,57.0,Male,Basic,1.62,17.0,Africa,Mobile,8.99,1,Crypto,2,0.09,Action

# 2. Missing value audit

In [4]:
missing = pd.DataFrame(index=["Missing", "Percentage"], columns=dataset.columns)
for columnname in dataset.columns:
    missing.loc["Missing", columnname] = dataset[columnname].isnull().sum()
    missing.loc["Percentage", columnname] = dataset[columnname].isnull().sum() / len(dataset) * 100
missing = missing.T
missing

                       Missing Percentage
customer_id                  0        0.0
age                        200        4.0
gender                       0        0.0
subscription_type          200        4.0
watch_hours                300        6.0
last_login_days            250        5.0
region                     150        3.0
device                     200        4.0
monthly_fee                150        3.0
churned                      0        0.0
payment_method             150        3.0
number_of_profiles           0        0.0
avg_watch_time_per_day     300        6.0
favorite_genre             200        4.0

#  Duplicates

In [5]:
dataset.isna().sum()

customer_id                 0
age                       200
gender                      0
subscription_type         200
watch_hours               300
last_login_days           250
region                    150
device                    200
monthly_fee               150
churned                     0
payment_method            150
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre            200
dtype: int64

In [6]:
print("Duplications :",dataset.duplicated().sum())

Duplications : 0

# 3. Recovering subscription_type and monthly_fee

# Fixing subscription_type  based on monthly fee
# If monthly fee is 8.99= Basic
# If monthly fee is 13.99= Standard
# If monthly fee is 17.99= Premium

In [7]:
dataset.loc[(dataset["subscription_type"].isnull())&(dataset["monthly_fee"]==8.99),["subscription_type","monthly_fee"]]

     subscription_type  monthly_fee
131                NaN         8.99
238                NaN         8.99
270                NaN         8.99
320                NaN         8.99
473                NaN         8.99
483                NaN         8.99
510                NaN         8.99
599                NaN         8.99
657                NaN         8.99
705                NaN         8.99
762                NaN         8.99
786                NaN         8.99
841                NaN         8.99
881                NaN         8.99
958                NaN         8.99
1009               NaN         8.99
1029               NaN         8.99
1047               NaN         8.99
1075               NaN         8.99
1247               NaN         8.99
1296               NaN         8.99
1391               NaN         8.99
1433               NaN         8.99
1528               NaN         8.99
1884               NaN         8.99
1885               NaN         8.99
1949               NaN         8.99
2063               NaN         8.99
2185               NaN         8.99
2329               NaN         8.99
2343               NaN         8.99
2441               NaN         8.99
2649               NaN         8.99
2846               NaN         8.99
2898               NaN         8.99
3183               NaN         8.99
3277               NaN         8.99
3286               NaN         8.99
3419               NaN         8.99
3647               NaN         8.99
3710               NaN         8.99
3753               NaN         8.99
3927               NaN         8.99
3935               NaN         8.99
3958               NaN         8.99
3962               NaN         8.99
4089               NaN         8.99
4520               NaN         8.99
4642               NaN         8.99
4679               NaN         8.99
4734               NaN         8.99
4831               NaN         8.99
4845               NaN         8.99
4925               NaN         8.99
4949               NaN         8.99

In [8]:
dataset.loc[(dataset["subscription_type"].isnull())&(dataset["monthly_fee"]==8.99),["subscription_type"]] ="Basic"

In [9]:
dataset.loc[(dataset["subscription_type"].isnull())&(dataset["monthly_fee"]==13.99),["subscription_type","monthly_fee"]]

     subscription_type  monthly_fee
5                  NaN        13.99
31                 NaN        13.99
158                NaN        13.99
217                NaN        13.99
249                NaN        13.99
...                ...          ...
4802               NaN        13.99
4870               NaN        13.99
4908               NaN        13.99
4975               NaN        13.99
4991               NaN        13.99

[63 rows x 2 columns]

In [10]:
dataset.loc[(dataset["subscription_type"].isnull())&(dataset["monthly_fee"]==13.99),["subscription_type"]]="Standard"

In [11]:
dataset.loc[(dataset["subscription_type"].isnull())&(dataset["monthly_fee"]==13.99),["subscription_type","monthly_fee"]]

Empty DataFrame
Columns: [subscription_type, monthly_fee]
Index: []

In [12]:
dataset.loc[(dataset["subscription_type"].isnull())&(dataset["monthly_fee"]==17.99),["subscription_type","monthly_fee"]]

     subscription_type  monthly_fee
127                NaN        17.99
154                NaN        17.99
289                NaN        17.99
307                NaN        17.99
379                NaN        17.99
...                ...          ...
4551               NaN        17.99
4560               NaN        17.99
4610               NaN        17.99
4835               NaN        17.99
4971               NaN        17.99

[78 rows x 2 columns]

In [13]:
dataset.loc[(dataset["subscription_type"].isnull())&(dataset["monthly_fee"]==17.99),["subscription_type"]]="Premium"

In [14]:
dataset.isnull().sum()

customer_id                 0
age                       200
gender                      0
subscription_type           4
watch_hours               300
last_login_days           250
region                    150
device                    200
monthly_fee               150
churned                     0
payment_method            150
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre            200
dtype: int64

## Rows missing both subscription_type and monthly_fee

In [15]:
dataset["subscription_type"].mode()[0]

'Premium'

In [16]:
dataset.loc[(dataset["subscription_type"].isnull())&(dataset["monthly_fee"].isnull()),["subscription_type","monthly_fee"]]

     subscription_type  monthly_fee
45                 NaN          NaN
1566               NaN          NaN
2234               NaN          NaN
3991               NaN          NaN

In [17]:
dataset.loc[dataset["subscription_type"].isnull(), "subscription_type"] = dataset["subscription_type"].mode()[0]

In [18]:
dataset.isnull().sum()

customer_id                 0
age                       200
gender                      0
subscription_type           0
watch_hours               300
last_login_days           250
region                    150
device                    200
monthly_fee               150
churned                     0
payment_method            150
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre            200
dtype: int64

## Fixing monthly_fee based on subscription_type

In [19]:
dataset.loc[dataset["monthly_fee"].isnull(),["subscription_type","monthly_fee"]]

     subscription_type  monthly_fee
19            Standard          NaN
23            Standard          NaN
45             Premium          NaN
82            Standard          NaN
94             Premium          NaN
...                ...          ...
4888           Premium          NaN
4932             Basic          NaN
4944           Premium          NaN
4951          Standard          NaN
4959           Premium          NaN

[150 rows x 2 columns]

In [20]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"]=="Basic"),["monthly_fee","subscription_type"]]

      monthly_fee subscription_type
147           NaN             Basic
152           NaN             Basic
252           NaN             Basic
385           NaN             Basic
435           NaN             Basic
438           NaN             Basic
713           NaN             Basic
731           NaN             Basic
750           NaN             Basic
825           NaN             Basic
859           NaN             Basic
933           NaN             Basic
1130          NaN             Basic
1182          NaN             Basic
1221          NaN             Basic
1569          NaN             Basic
1572          NaN             Basic
1609          NaN             Basic
1621          NaN             Basic
1713          NaN             Basic
1717          NaN             Basic
1895          NaN             Basic
2245          NaN             Basic
2246          NaN             Basic
2327          NaN             Basic
2410          NaN             Basic
2544          NaN             Basic
2616          NaN             Basic
2754          NaN             Basic
2877          NaN             Basic
2912          NaN             Basic
2944          NaN             Basic
2963          NaN             Basic
2969          NaN             Basic
2971          NaN             Basic
3034          NaN             Basic
3103          NaN             Basic
3139          NaN             Basic
3442          NaN             Basic
3473          NaN             Basic
3616          NaN             Basic
3638          NaN             Basic
3659          NaN             Basic
3786          NaN             Basic
4197          NaN             Basic
4259          NaN             Basic
4402          NaN             Basic
4442          NaN             Basic
4476          NaN             Basic
4486          NaN             Basic
4558          NaN             Basic
4932          NaN             Basic

In [21]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"] == "Basic"), ["monthly_fee", "subscription_type"]]

      monthly_fee subscription_type
147           NaN             Basic
152           NaN             Basic
252           NaN             Basic
385           NaN             Basic
435           NaN             Basic
438           NaN             Basic
713           NaN             Basic
731           NaN             Basic
750           NaN             Basic
825           NaN             Basic
859           NaN             Basic
933           NaN             Basic
1130          NaN             Basic
1182          NaN             Basic
1221          NaN             Basic
1569          NaN             Basic
1572          NaN             Basic
1609          NaN             Basic
1621          NaN             Basic
1713          NaN             Basic
1717          NaN             Basic
1895          NaN             Basic
2245          NaN             Basic
2246          NaN             Basic
2327          NaN             Basic
2410          NaN             Basic
2544          NaN             Basic
2616          NaN             Basic
2754          NaN             Basic
2877          NaN             Basic
2912          NaN             Basic
2944          NaN             Basic
2963          NaN             Basic
2969          NaN             Basic
2971          NaN             Basic
3034          NaN             Basic
3103          NaN             Basic
3139          NaN             Basic
3442          NaN             Basic
3473          NaN             Basic
3616          NaN             Basic
3638          NaN             Basic
3659          NaN             Basic
3786          NaN             Basic
4197          NaN             Basic
4259          NaN             Basic
4402          NaN             Basic
4442          NaN             Basic
4476          NaN             Basic
4486          NaN             Basic
4558          NaN             Basic
4932          NaN             Basic

In [22]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"] == "Basic"), ["monthly_fee"]]=8.99

In [23]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"] == "Basic"), ["monthly_fee", "subscription_type"]]

Empty DataFrame
Columns: [monthly_fee, subscription_type]
Index: []

In [24]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"] == "Standard"), ["monthly_fee", "subscription_type"]]

      monthly_fee subscription_type
19            NaN          Standard
23            NaN          Standard
82            NaN          Standard
231           NaN          Standard
454           NaN          Standard
603           NaN          Standard
615           NaN          Standard
625           NaN          Standard
674           NaN          Standard
733           NaN          Standard
798           NaN          Standard
910           NaN          Standard
920           NaN          Standard
1067          NaN          Standard
1110          NaN          Standard
1172          NaN          Standard
1178          NaN          Standard
1201          NaN          Standard
1249          NaN          Standard
1263          NaN          Standard
1318          NaN          Standard
1376          NaN          Standard
1473          NaN          Standard
1493          NaN          Standard
1780          NaN          Standard
1933          NaN          Standard
2044          NaN          Standard
2235          NaN          Standard
2266          NaN          Standard
2332          NaN          Standard
2571          NaN          Standard
2702          NaN          Standard
2945          NaN          Standard
3262          NaN          Standard
3322          NaN          Standard
3368          NaN          Standard
3468          NaN          Standard
3507          NaN          Standard
3590          NaN          Standard
3603          NaN          Standard
3620          NaN          Standard
3795          NaN          Standard
3854          NaN          Standard
3947          NaN          Standard
4066          NaN          Standard
4163          NaN          Standard
4185          NaN          Standard
4203          NaN          Standard
4413          NaN          Standard
4530          NaN          Standard
4763          NaN          Standard
4951          NaN          Standard

In [25]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"] == "Standard"), ["monthly_fee"]]=13.99

In [26]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"] == "Standard"), ["monthly_fee", "subscription_type"]]

Empty DataFrame
Columns: [monthly_fee, subscription_type]
Index: []

In [27]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"] == "Premium"), ["monthly_fee", "subscription_type"]]

      monthly_fee subscription_type
45            NaN           Premium
94            NaN           Premium
100           NaN           Premium
236           NaN           Premium
299           NaN           Premium
391           NaN           Premium
541           NaN           Premium
557           NaN           Premium
632           NaN           Premium
659           NaN           Premium
818           NaN           Premium
1112          NaN           Premium
1364          NaN           Premium
1430          NaN           Premium
1462          NaN           Premium
1556          NaN           Premium
1566          NaN           Premium
1568          NaN           Premium
2070          NaN           Premium
2234          NaN           Premium
2350          NaN           Premium
2421          NaN           Premium
2521          NaN           Premium
2675          NaN           Premium
2739          NaN           Premium
2787          NaN           Premium
2854          NaN           Premium
2891          NaN           Premium
2902          NaN           Premium
3038          NaN           Premium
3328          NaN           Premium
3455          NaN           Premium
3940          NaN           Premium
3991          NaN           Premium
4006          NaN           Premium
4082          NaN           Premium
4093          NaN           Premium
4210          NaN           Premium
4390          NaN           Premium
4473          NaN           Premium
4517          NaN           Premium
4598          NaN           Premium
4847          NaN           Premium
4888          NaN           Premium
4944          NaN           Premium
4959          NaN           Premium

In [28]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"] == "Premium"), ["monthly_fee"]]=17.99

In [29]:
dataset.loc[(dataset["monthly_fee"].isnull()) & (dataset["subscription_type"] == "Premium"), ["monthly_fee", "subscription_type"]]

Empty DataFrame
Columns: [monthly_fee, subscription_type]
Index: []

In [30]:
dataset.isnull().sum()

customer_id                 0
age                       200
gender                      0
subscription_type           0
watch_hours               300
last_login_days           250
region                    150
device                    200
monthly_fee                 0
churned                     0
payment_method            150
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre            200
dtype: int64

# 4. Filling remaining missing values
## age – median

In [31]:
dataset["age"].median()

44.0

In [32]:
dataset["age"].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Name: age, Length: 5000, dtype: bool

In [33]:
dataset["age"] = dataset["age"].fillna(44)

In [34]:
dataset.isnull().sum()

customer_id                 0
age                         0
gender                      0
subscription_type           0
watch_hours               300
last_login_days           250
region                    150
device                    200
monthly_fee                 0
churned                     0
payment_method            150
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre            200
dtype: int64

## region – mode

In [35]:
dataset["region"].mode()[0]

'South America'

In [36]:
dataset.loc[(dataset["region"].isnull()),"region"]=dataset["region"].mode()[0]

In [37]:
dataset.isnull().sum()

customer_id                 0
age                         0
gender                      0
subscription_type           0
watch_hours               300
last_login_days           250
region                      0
device                    200
monthly_fee                 0
churned                     0
payment_method            150
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre            200
dtype: int64

## device – mode

In [38]:
dataset["device"].mode()[0]

'Tablet'

In [39]:
dataset.loc[(dataset["device"].isnull()),"device"]=dataset["device"].mode()[0]

In [40]:
dataset.isnull().sum()

customer_id                 0
age                         0
gender                      0
subscription_type           0
watch_hours               300
last_login_days           250
region                      0
device                      0
monthly_fee                 0
churned                     0
payment_method            150
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre            200
dtype: int64

## favorite_genre – mode

In [41]:
dataset["favorite_genre"].mode()[0]

'Drama'

In [42]:
dataset.loc[(dataset["favorite_genre"].isnull()),"favorite_genre"]=dataset["favorite_genre"].mode()[0]

In [43]:
dataset.isnull().sum()

customer_id                 0
age                         0
gender                      0
subscription_type           0
watch_hours               300
last_login_days           250
region                      0
device                      0
monthly_fee                 0
churned                     0
payment_method            150
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre              0
dtype: int64

## payment_method – mode

In [44]:
dataset["payment_method"].mode()[0]

'Debit Card'

In [45]:
dataset.loc[(dataset["payment_method"].isnull()),"payment_method"]=dataset["payment_method"].mode()[0]

In [46]:
dataset.isnull().sum()

customer_id                 0
age                         0
gender                      0
subscription_type           0
watch_hours               300
last_login_days           250
region                      0
device                      0
monthly_fee                 0
churned                     0
payment_method              0
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre              0
dtype: int64

## watch_hours – median

In [47]:
dataset["watch_hours"].median()

8.02

In [48]:
dataset.loc[(dataset["watch_hours"].isnull()),"watch_hours"] = dataset["watch_hours"].median()

In [49]:
dataset.isnull().sum()

customer_id                 0
age                         0
gender                      0
subscription_type           0
watch_hours                 0
last_login_days           250
region                      0
device                      0
monthly_fee                 0
churned                     0
payment_method              0
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre              0
dtype: int64

## last_login_days – median

In [50]:
dataset.loc[(dataset["last_login_days"].isnull())& (dataset["churned"]==0),["last_login_days","churned"]]

      last_login_days  churned
23                NaN        0
36                NaN        0
51                NaN        0
67                NaN        0
70                NaN        0
...               ...      ...
4914              NaN        0
4932              NaN        0
4966              NaN        0
4976              NaN        0
4979              NaN        0

[131 rows x 2 columns]

In [51]:
dataset.loc[dataset["churned"] == 0, "last_login_days"].median()

19.0

In [52]:
dataset.loc[dataset["churned"] == 1, "last_login_days"].median()

41.0

In [53]:
dataset.loc[dataset["last_login_days"].isnull(), "last_login_days"] = dataset["last_login_days"].median()

In [54]:
dataset.isnull().sum()

customer_id                 0
age                         0
gender                      0
subscription_type           0
watch_hours                 0
last_login_days             0
region                      0
device                      0
monthly_fee                 0
churned                     0
payment_method              0
number_of_profiles          0
avg_watch_time_per_day    300
favorite_genre              0
dtype: int64

## avg_watch_time_per_day – median

In [55]:
dataset.loc[dataset["churned"] == 0, "avg_watch_time_per_day"]

2       1.48
5       0.51
6       0.66
8        NaN
10      0.42
        ...
4991    0.27
4994    0.47
4995    4.10
4996    3.08
4998    2.28
Name: avg_watch_time_per_day, Length: 2485, dtype: float64

In [56]:
dataset.loc[dataset["churned"] == 0, "avg_watch_time_per_day"].median()

0.72

In [57]:
dataset.loc[dataset["avg_watch_time_per_day"].isnull(), "avg_watch_time_per_day"] = dataset["avg_watch_time_per_day"].median()

In [58]:
dataset.isnull().sum()

customer_id               0
age                       0
gender                    0
subscription_type         0
watch_hours               0
last_login_days           0
region                    0
device                    0
monthly_fee               0
churned                   0
payment_method            0
number_of_profiles        0
avg_watch_time_per_day    0
favorite_genre            0
dtype: int64

# 5. Final check

In [59]:
dataset["churned"].value_counts()

churned
1    2515
0    2485
Name: count, dtype: int64

# Changing avg_watch_time_per_day from percentage to Mins

In [64]:
(dataset["avg_watch_time_per_day"] * 60).round().astype(int)

0        29
1         2
2        89
3        21
4         8
       ...
4995    246
4996    185
4997     20
4998    137
4999      5
Name: avg_watch_time_per_day, Length: 5000, dtype: int64

In [65]:
dataset["avg_watch_time_per_day"]=(dataset["avg_watch_time_per_day"] * 60).round().astype(int)

In [66]:
dataset.to_csv("Netflix_clean.csv", index=False)